config/routes.rb
Epilab::Application.routes.draw do
  devise_for :users

  root to: 'application#welcome'
  match '/about' => 'application#about', via: :get
  match '/year_report_statistic' => 'application#year_report_statistic', via: :get
  # PATIENTS DASHBOARD
  get "/patient" => "patients#today", as: :patient_root
  resource :patient, only: [:show, :edit, :update] do
    resources :medicines
    resources :seizures
    resource :consultation

    get :statistic
    post "/medications/:id/taken" => "medications#taken", as: :take_medication
    post "/medications/:id/rejected" => "medications#rejected", as: :reject_medication
  end



  # ADMIN DASHBOARD
  namespace :admin do
    get "/" => "patients#index", as: :root

    resources :patients, only: [:index, :show] do
      get :search, on: :collection
    end

    resources :users

    resources :doctors, except: [:show] do
      post :sort, on: :collection
    end

    resource :clinic, only: [:show, :update]
    resources :dialogs do
      resources :consultations, only: :create, on: :member
    end

    resources :medicines, except: [:show] do
      post :sort, on: :collection
    end

    resources :dictionaries do
      collection do
        post :sort
      end
    end
  end

  # API METHODS
  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      resources :patients, only: :show do
        member do
          get :calendar
          get :info
          get :graphics
          post :report
        end
        resources :medications, only: [:index] do
          collection do
            get :graphic
            get :today
            get :rejects
          end
          member do
            post :taken
            post :rejected
          end
        end
        resources :seizures, only: [:create, :show, :destroy, :update] do
          collection do
            get :graphic
            get :today
            get :daytime_statistic
            get :average_duration
          end
        end
        resources :patient_medicines, path: :medicines, only: [:index, :create, :destroy, :update]
        resources :consultations, only: [:index, :create]
      end
      resources :medicines, only: [:index, :create]
      resources :device_tokens, only: [:create]

      get "dictionary/seizure/types" => "dictionary#index", as: :seizure_types, defaults: { bookmark: "seizure_type" }
      get "dictionary/seizure/reasons" => "dictionary#index", as: :seizure_reasons, defaults: { bookmark: "seizure_reason" }
      get "doctors" => "doctors#index"
      get "clinic" => "clinic#show"

      devise_scope :user do
        post "user/login" => "devise/sessions#create", as: :login
        post "user/logout" => "devise/sessions#destroy", as: :destroy
        post "user/signup" => "devise/registrations#create", as: :signup
        post "user/update" => "devise/registrations#update", as: :update_profile
        post "user/password/restore" => "devise/passwords#create", as: :restore_password
      end

    end
  end
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
	include AlterMvc::Concerns::Querable
	include AlterMvc::Concerns::Presentable
	include AlterMvc::Concerns::ServiceObjectable
	acts_as_positioned by_field: :patient_id

	default_scope { order position: :asc }
	scope :for_patient, ->(patient_id){ where "patient_id = :patient_id OR patient_id IS NULL", patient_id: patient_id }
	scope :ordered_by_patient, ->{ reorder "patient_id DESC, position ASC, created_at DESC" }
	scope :system, ->{ where "patient_id IS NULL" }

	has_many :medications
	has_many :patient_medicines

	belongs_to :patient, class_name: "User", primary_key: :patient_id
	
end
# == Schema Information
#
# Table name: medicines
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  position   :integer          default(0), not null
#  patient_id :integer
#

#

app/controllers/admin/medicines_controller.rb
class Admin::MedicinesController < AdminController
  authorize_resource

	self.responder = Admin::MedicineResponder
	respond_to :html

	before_filter :find_medicine, only: [:destroy]

  def index
  	@medicines = Medicine.system
  end

  def new
  	@medicine = Medicine.new
  end

  def create
		@medicine = Medicines::Adding.new(params: new_medicine_params).execute
		respond_with @medicine
  end

  def destroy
  	@medicine.destroy
  	respond_with @medicine
  end

  def sort
    Sortable.new(object: :medicine, id: params[:object][:id], position: params[:object][:position]).execute
    render nothing: true
  end

private
	def new_medicine_params
		@_medicine_params ||= MedicineParameterSanitizer.new(params)
	end

	def find_medicine
		@medicine ||= Medicine.find params[:id]
	end
end

app/controllers/api/v1/medicines_controller.rb
class API::V1::MedicinesController < ApiController
	authorize_resource

	def index
		medicines = current_user.available_medicines
		render status: 200, json: medicines
	end

	def create
		use_case = Medicines::Adding.new(params: new_medicine_params, user_id: current_user.id)
		if use_case.valid?
			render status: 200, json: use_case.execute
		else
			render status: 401, json: { errors: use_case.error_messages }
		end
	end

private
	def new_medicine_params
		@_medicine_params ||= MedicineParameterSanitizer.new(params)
	end
	
end

app/controllers/medicines_controller.rb
class MedicinesController < DashboardController
	self.responder = PatientMedicineResponder
	respond_to :html

	def index
		@medicines = current_user.medicines.includes(:medicine)
	end

	def new
		@medicine = current_user.medicines.new
	end

	def create
		@medicine = Patients::Medicines::Create.new(patient_id: current_user.id, params: medicine_params).execute
		respond_with @medicine
	end

	def destroy
		medicine = current_user.medicines.find params[:id]
		medicine.finish! if medicine
		respond_with medicine
	end

	def edit
		@medicine = PatientMedicine.find params[:id]
	end

	def update
		use_case = Patients::Medicines::Update.new(medicine_id: params[:id], params: medicine_params)
		@medicine = use_case.execute
		if use_case.valid?
			redirect_to patient_medicines_path
		else
			render :edit
		end
	end

private
	def medicine_params
		@medicine_params ||= PatientMedicineParameterSanitizer.new params
	end
end

app/views/medicines/edit.html.slim
h2 Редактирование препарата

.row ng-controller="PatientMedicinesCtrl" ng-init='receptions=#{@medicine.reception.present? ? @medicine.reception.to_json : [{time: "00:00"}]}'
	.col-md-12
		- if @medicine.errors.count > 0
			- @medicine.errors.full_messages.each do |err|
				div.text-danger = err
	= simple_form_for @medicine, url: patient_medicine_path(@medicine), method: :put, defaults: { input_html: { class: "form-control" }, label: false } do |f|

		.col-md-6
			.form-group class="#{'has-error' if !@medicine.errors[:medicine_id].empty?}"
				label Препарат
				select.form-control ng-options="medicine.id as medicine.title for medicine in medicines" ng-model="medicine" disabled="true"

			= f.hidden_field :reception, value: "{{receptions}}"

			h6 Расписание
			= f.input :beginning_at, as: :flat_datepicker, placeholder: "Начало курса", disabled: true
			= f.input :periodicity, placeholder: "Периодичность", label: "Периодичность", as: :select, collection: PatientMedicine.periodicities.keys, include_blank: false, disabled: true
		.col-md-6
			h6 Время и дозировка
			.clearfix
			div ng-repeat="reception in receptions" class="reception" ng-class="{'acceptable': is_acceptable(reception)}"
				= select_tag "time[]", options_for_select(PatientMedicineQuery.reception_times), include_blank: false, "ng-model" => "reception.time"
				= text_field_tag "dosage[]", nil, "ng-model" => "reception.dosage", placeholder: "доза"
				center мл
			.reception.add ng-click="add_reception()" +
		.col-md-12
			.form-actions = f.submit "Добавить", class: "btn btn-huge btn-wide btn-primary"


	script type="text/ng-template" id="custom_medicine.html"
		.modal-header
			h4 Свой препарат
		.modal-body
			.form-group
				= text_field_tag :title, nil, class: "form-control", "ng-model" => "medicine.title", placeholder: "Название препарата.."
		.modal-footer
			= link_to "Отмена", '#', class: "btn btn-default", "ng-click" => "cancel()"
			= link_to "Сохранить", 'javascript:void(0);', class: "btn btn-primary", "ng-click" => "ok()"

app/views/medicines/index.html.slim
h3
	| Принимаемые препараты
	= link_to new_patient_medicine_path, class: "btn btn-primary btn-sm btn-wide btn-epi pull-right" do
		i.fui-plus-inverted
		| Добавить препарат

- if @medicines.any?
	table.table.nowraped
		thead
			tr
				th Препарат
				th.text-right Начало приема
				th.text-right Периодичность
				th.text-right Ближайший прием
				th
		tbody= @medicines.rendering as: :table_row, with: self
- else
	= custom_message "ВЫ НЕ ПРИНИМАЕТЕ НИКАКИХ ПРЕПАРАТОВ"

app/views/medicines/new.html.slim
h2 Новый препарат

.row ng-controller="PatientMedicinesCtrl" ng-init='receptions=#{@medicine.reception.present? ? @medicine.reception.to_json : [{time: "00:00"}]}'
	= simple_form_for @medicine, url: patient_medicines_path, defaults: { input_html: { class: "form-control" }, label: false } do |f|
		.col-md-6
			.form-group class="#{'has-error' if !@medicine.errors[:medicine_id].empty?}"
				label
					| Препарат 
					= link_to "Добавить", 'javascript:void(0);', "ng-click" => "custom_medicine()"
				select.form-control ng-options="medicine.id as medicine.title for medicine in medicines" ng-model="medicine" ng-change="loadMedicineDosages(selected_medicine)"
				small.help-inline.text-danger = @medicine.errors[:medicine_id].join('\n') if !@medicine.errors[:reception].empty?

			= f.hidden_field :reception, value: "{{receptions}}"

			h6 Расписание
			= f.hidden_field :medicine_id, value: "{{medicine}}"
			= f.input :beginning_at, as: :flat_datepicker, placeholder: "Начало курса"
			= f.input :periodicity, placeholder: "Периодичность", label: "Периодичность", as: :select, collection: PatientMedicine.periodicities.map {|k,v| [k,v]}, include_blank: false
			= f.input :remind, as: :select, label: "Напоминать?"
		.col-md-6
			h6 Время и дозировка
			small.text-danger = @medicine.errors[:reception].join('\n') if !@medicine.errors[:reception].empty?
			.clearfix
			div ng-repeat="reception in receptions" class="reception" ng-class="{'acceptable': is_acceptable(reception)}"
				= select_tag "time[]", options_for_select(PatientMedicineQuery.reception_times), include_blank: false, "ng-model" => "reception.time"
				= text_field_tag "dosage[]", nil, "ng-model" => "reception.dosage", placeholder: "доза"
				center мл
			.reception.add ng-click="add_reception()" +
		.col-md-12
			.form-actions = f.submit "Добавить", class: "btn btn-huge btn-wide btn-primary"


	script type="text/ng-template" id="custom_medicine.html"
		.modal-header
			h4 Свой препарат
		.modal-body
			.form-group
				= text_field_tag :title, nil, class: "form-control", "ng-model" => "medicine.title", placeholder: "Название препарата.."
		.modal-footer
			= link_to "Отмена", '#', class: "btn btn-default", "ng-click" => "cancel()"
			= link_to "Добавить", 'javascript:void(0);', class: "btn btn-primary", "ng-click" => "ok()"