config/routes.rb
Epilab::Application.routes.draw do
  devise_for :users

  root to: 'application#welcome'
  match '/about' => 'application#about', via: :get
  match '/year_report_statistic' => 'application#year_report_statistic', via: :get
  # PATIENTS DASHBOARD
  get "/patient" => "patients#today", as: :patient_root
  resource :patient, only: [:show, :edit, :update] do
    resources :medicines
    resources :seizures
    resource :consultation

    get :statistic
    post "/medications/:id/taken" => "medications#taken", as: :take_medication
    post "/medications/:id/rejected" => "medications#rejected", as: :reject_medication
  end



  # ADMIN DASHBOARD
  namespace :admin do
    get "/" => "patients#index", as: :root

    resources :patients, only: [:index, :show] do
      get :search, on: :collection
    end

    resources :users

    resources :doctors, except: [:show] do
      post :sort, on: :collection
    end

    resource :clinic, only: [:show, :update]
    resources :dialogs do
      resources :consultations, only: :create, on: :member
    end

    resources :medicines, except: [:show] do
      post :sort, on: :collection
    end

    resources :dictionaries do
      collection do
        post :sort
      end
    end
  end

  # API METHODS
  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      resources :patients, only: :show do
        member do
          get :calendar
          get :info
          get :graphics
          post :report
        end
        resources :medications, only: [:index] do
          collection do
            get :graphic
            get :today
            get :rejects
          end
          member do
            post :taken
            post :rejected
          end
        end
        resources :seizures, only: [:create, :show, :destroy, :update] do
          collection do
            get :graphic
            get :today
            get :daytime_statistic
            get :average_duration
          end
        end
        resources :patient_medicines, path: :medicines, only: [:index, :create, :destroy, :update]
        resources :consultations, only: [:index, :create]
      end
      resources :medicines, only: [:index, :create]
      resources :device_tokens, only: [:create]

      get "dictionary/seizure/types" => "dictionary#index", as: :seizure_types, defaults: { bookmark: "seizure_type" }
      get "dictionary/seizure/reasons" => "dictionary#index", as: :seizure_reasons, defaults: { bookmark: "seizure_reason" }
      get "doctors" => "doctors#index"
      get "clinic" => "clinic#show"

      devise_scope :user do
        post "user/login" => "devise/sessions#create", as: :login
        post "user/logout" => "devise/sessions#destroy", as: :destroy
        post "user/signup" => "devise/registrations#create", as: :signup
        post "user/update" => "devise/registrations#update", as: :update_profile
        post "user/password/restore" => "devise/passwords#create", as: :restore_password
      end

    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	include AlterMvc::Concerns::Querable
	include AlterMvc::Concerns::Presentable
	include AlterMvc::Concerns::ServiceObjectable
	include Users::Constants

	attr_accessor :current_password

	has_attached_file :photo, styles: { medium: "300x300#", thumb: "160x160#", small: "40x40#" }, default_url: "/images/icons/default.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  default_scope { order id: :asc }

	before_save :ensure_authentication_token

	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :validatable

	has_many :medicines, class_name: PatientMedicine
	has_many :medications, foreign_key: :patient_id
	has_many :seizures, foreign_key: :patient_id
	has_many :consultations, foreign_key: :patient_id
	has_many :device_tokens

	validates :first_name, :last_name, :role, presence: true
	validates :role, inclusion: { in: ROLES }
	validates :sex, inclusion: { in: SEXES }, allow_nil: true
	validates :password, confirmation: true
	validates :birthday, date: true, allow_nil: true

	DETAILS.each {|param| store_accessor :details, param }

	after_initialize do
		self.sex = SEXES.first unless self.sex
		self.role = "patient" unless self.role
		self.is_watcher = false if self.patient? && !self.is_watcher.present?
	end

	def ensure_authentication_token
		self.authentication_token = generate_authentication_token if self.authentication_token.blank?
	end

private
	def generate_authentication_token
		loop do
			token = Devise.friendly_token
			break token unless UserQuery.find_by_authentication_token(token)
		end
	end

end
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string(255)
#  last_name              :string(255)
#  email                  :string(255)
#  role                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  details                :hstore
#  photo_file_name        :string(255)
#  photo_content_type     :string(255)
#  photo_file_size        :integer
#  photo_updated_at       :datetime
#  seizures_count         :integer          default(0), not null
#  authentication_token   :string(255)
#  sign_in_count          :integer
#  medicines_count        :integer          default(0), not null
#

#

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	load_and_authorize_resource

	self.responder = Admin::UserResponder
	respond_to :html

	def index
		@users = User.all
	end

	def destroy
		@user.destroy
		respond_with @user
	end

	def update
		resource = Patients::UpdateProfile.new(id: @user.id, params: user_params).execute
		respond_with resource
	end

	def new; end

	def create; end

private
	def user_params
		UserParameterSanitizer.new params
	end

end

app/controllers/user/parameter_sanitizer.rb
class User::ParameterSanitizer < Devise::ParameterSanitizer

  def sign_up
    default_params.permit :first_name, :last_name, :birthday, :email, :password, :sex, :is_watcher
  end

  def account_update
    default_params.permit!
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/render/_admin_row.html.slim
tr
	td 
		= link_to edit_admin_user_path(user) do
			= image_tag user.photo.url(:small)
			= user.full_name
	td
		span.label class="label-#{user.role_label_class}" = user.draw_role
	td = user.email
	td = l user.created_at, format: "%d %b %Y %H:%M"
	td.text-right
		= link_to "Удалить", admin_user_path(user), method: :delete, "data-confirm" => TranslationHelper::confirm_destroy(:doctor, title: user.full_name)

app/views/users/render/_doctor_table_row.html.slim
tr id=user.id
	td.draggable
		i.fui-list
	td = user.full_name
	td.text-right
		= link_to doctor_path(user), method: :delete, "data-confirm" => TranslationHelper::confirm_destroy(:doctor, title: user.full_name) do
			i.fui-trash

app/views/users/render/_patient_card.html.slim
javascript:
	window.patient_id = #{@patient.id}

= javascript_include_tag "medications_graphic", "seizures_graphic"

h2
	= user.full_name
	.btn-group.pull-right data-toggle="buttons" style="margin-top: 17px;"
		- %w(week month quarter half year).each do |period|
			label.btn.btn-primary class="#{'active' if period == 'week'}"
				= radio_button_tag :period, period
				= TranslationHelper.period period

dl.dl-horizontal
	dt Email
	dd = user.email
	dt Пол
	dd = user.draw_sex
	dt Возраст
	dd = user.age
	dt Лекарства
	dd = user.medicines.map(&:draw_title).join(", ")

#medication-graphic
#seizures-graphic

app/views/users/render/_patient_table_row.html.slim
tr
	td 
		= link_to admin_patient_path(user) do
			= image_tag user.photo.url(:small)
			= user.full_name
	td = user.email
	td = user.age
	td = user.sex_letter
	td = user.seizures_count
	td = user.medicines_count
	td